openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/PabloHenriquedaSilvaAndrade/Slitree/1.0.0
info:
  version: '1.0.0'
  title: home-iot-api
  description: The API for the EatBacon IOT project
paths:
  /users/register:
    post:
      tags:
        - Users
      description: create a new user
      parameters:
        - name: id
          description: User object
          in: path
          required: true
          schema:
            type: object
            required:
              - email
              - name
              - password
            properties:
              email:
                type: string
              name:
                type: string
              password:
                type: string
      responses:
        200:
          description: Sucessfully created

  /auth:
    post:
      tags:
        - Auth
      description: Logs in a user
      parameters:
        - name: login
          description: Login object
          in: path
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'

  /posts:
    post:
      tags:
        - Posts
      description: create a new post
      parameters:
        - in: path
          name: post
          required: true
          schema:
            type: object
            required:
              - title
              - description
              - type
            properties:
              title:
                type: string
              description:
                type: string
              type:
                type: string
                enum:
                  - edital
                  - noticia
                  - divulgacao
      responses:
        200:
          description: Successfully created

  /posts/index:
    get:
      tags:
        - Posts
      description: Returns all posts
      responses:
        200:
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

  /post/filter?type={type}&tam={tam}&pag={pag}&search={search}:
    get:
      tags:
        - Posts
      description: Returns a filtered list of posts
      parameters:
        - in: path
          name: type
          required: true
          schema:
            type: string
            enum:
              - edital
              - noticia
              - divulgacao
        - in: path
          name: tam
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: pag
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: search
          required: true
          schema:
            type: string

      responses:
        200:
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

  /post/{id}:
    get:
      tags:
        - Posts
      description: Returns a single post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: A single post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

    delete:
      tags:
        - Posts
      description: Deletes a post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successfully deleted

    put:
      tags:
        - Posts
      description: Updates a post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: post
          required: true
          schema:
            type: object
            required:
              - title
              - description
              - type
            properties:
              title:
                type: string
              description:
                type: string
              type:
                type: string
                enum:
                  - edital
                  - noticia
                  - divulgacao
      responses:
        200:
          description: Successfully updated

  /likes/{postId}:
    post:
      tags:
        - Like
      description: Like a post or undo a like
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successfully liked

  /likes/{postId}/count:
    get:
      tags:
        - Like
      description: Returns the number of likes of a post
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: The number of likes
          content:
            application/json:
              schema:
                type: integer
                format: int64

components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        type:
          type: string
